name: test-pipeline

on: push

env:
  DOTNET_VERSION: '8.0.101' # The .NET SDK version to use

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - run: ls -al
    
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: |
          dotnet publish NetDaemonApps\NetDaemonApps.csproj -c release
